version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: student-jobs-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-carlbarl}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Pyttegasvik24!}
      POSTGRES_DB: ${POSTGRES_DB:-studentjobs}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.0
    container_name: student-jobs-search
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
    volumes:
      - meilisearch-data:/meili_data
    ports:
      - "7700:7700"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # För utveckling - används inte i produktion
  pgadmin:
    image: dpage/pgadmin4
    container_name: student-jobs-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - postgres

  # Skapa en Redis-instans för caching och rate-limiting
  redis:
    image: redis:7-alpine
    container_name: student-jobs-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  meilisearch-data:
  pgadmin-data:
  redis-data: